---
name: hetzner/big-blue-button

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "apps/hetzner/big-blue-button/**"
      - ".github/workflows/packer-big-blue-button.yml"
      - "apps/shared/**"

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          arguments: -syntax-only
          target: apps/hetzner/big-blue-button/

      # build artifact
      - name: Build big-blue-button
        uses: hashicorp/packer-github-actions@master
        with:
          command: build
          arguments: "-color=false -on-error=abort"
          target: apps/hetzner/big-blue-button/
        env:
          HCLOUD_API_TOKEN: ${{ secrets.HCLOUD_API_TOKEN }}
  cleanup:
    runs-on: [self-hosted, Linux, X64]
    needs: packer
    steps:
      - uses: actions/checkout@v2
      - run: ./.github/cleanup.sh big-blue-button
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_API_TOKEN }}
