---
name: hetzner/nextcloud

on:
  push:
    paths:
      - "apps/hetzner/nextcloud/**"
      - ".github/workflows/packer-nextcloud.yml"
      - ".github/actions/build-image/**"
      - "apps/shared/**"
  schedule:
    - cron: "0 13 * * *"
  workflow_dispatch:

jobs:
  packer:
    runs-on: [self-hosted, Linux, X64]
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - uses: ./.github/actions/build-image
        with:
          app: nextcloud
          token: ${{ github.ref == 'refs/heads/main' && secrets.HCLOUD_API_TOKEN || secrets.HCLOUD_API_TOKEN_STAGING }}
